name: Naukri automation

on:
  schedule:
    - cron: "0 */4 * * *"  # every 4 hours (UTC)
  workflow_dispatch:
jobs:
  run-naukri:
    runs-on: ubuntu-latest
    
    env:
      NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug env
        run: |
          echo "USERNAME is set? $([[ -n \"$NAUKRI_USERNAME\" ]] && echo yes || echo no)"
          echo "PASSWORD is set? $([[ -n \"$NAUKRI_PASSWORD\" ]] && echo yes || echo no)"   

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run script
        run: node index.js
