name: Naukri automation

on:
  schedule:
    # Every 10 minutes between 09:00–11:00 IST (03:30–05:30 UTC)
    - cron: "30-50/10 3 * * *"  # 03:30, 03:40, 03:50 UTC  (09:00–09:20 IST)
    - cron: "*/10 4 * * *"      # 04:00–04:50 UTC         (09:30–10:20 IST)
    - cron: "0-20/10 5 * * *"   # 05:00, 05:10, 05:20 UTC (10:30–10:50 IST)

    # Otherwise every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch:
jobs:
  run-naukri:
    runs-on: ubuntu-latest
    environment: Naukri
    
    env:
      NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug env
        run: |
          echo "USERNAME is set? $([[ -n \"$NAUKRI_USERNAME\" ]] && echo yes || echo no)"
          echo "PASSWORD is set? $([[ -n \"$NAUKRI_PASSWORD\" ]] && echo yes || echo no)"   

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run script
        run: node index.js
